// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj98Xeq5kV4JGFNZUhNVsMSglNjyOKPhQ',
    appId: '1:528866748996:android:6e3274b7343c6ec4d82a11',
    messagingSenderId: '528866748996',
    projectId: 'sample-music-65323',
    databaseURL: 'https://sample-music-65323-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sample-music-65323.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB79H-EwndHfJtjgMh7hTUiHRYxcObdvZg',
    appId: '1:528866748996:ios:b052a2dd30161559d82a11',
    messagingSenderId: '528866748996',
    projectId: 'sample-music-65323',
    databaseURL: 'https://sample-music-65323-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sample-music-65323.firebasestorage.app',
    androidClientId: '528866748996-1g1r4m137uvplesq4hd0j1auq9et27j4.apps.googleusercontent.com',
    iosClientId: '528866748996-tm161h99tolamlueksnd3fq1k7pnb19o.apps.googleusercontent.com',
    iosBundleId: 'com.musichub.musicHub',
  );
}
